spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-learn
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10